# Generated by Django 2.1.7 on 2019-04-16 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('data_creacio', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mesura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Mesures',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Passa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(default='', max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Passes',
                'ordering': ['recepta__titol', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField()),
                ('foto', models.ImageField(default='/fotos/no-img2.jpg', upload_to='fotos/')),
                ('data_creacio', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data_programat', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data_consumit', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actiu', models.BooleanField(default=True)),
                ('thermomix', models.BooleanField(default=True)),
                ('dificultat', models.CharField(choices=[('F', 'Fàcil'), ('M', 'Mitjana'), ('D', 'Difícil')], default='F', max_length=1)),
                ('temps_preparacio', models.CharField(blank=True, max_length=7, null=True)),
                ('temps_total', models.CharField(blank=True, max_length=7, null=True)),
                ('racions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='receptes.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Receptes',
            },
        ),
        migrations.CreateModel(
            name='ReceptaIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveSmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptes', to='receptes.Ingredient')),
                ('recepta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptes.Recepta')),
            ],
        ),
        migrations.AddField(
            model_name='recepta',
            name='ingredients',
            field=models.ManyToManyField(through='receptes.ReceptaIngredient', to='receptes.Ingredient'),
        ),
        migrations.AddField(
            model_name='passa',
            name='recepta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='receptes.Recepta'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='mesura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receptes.Mesura'),
        ),
        migrations.AddField(
            model_name='comentari',
            name='recepta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to='receptes.Recepta'),
        ),
        migrations.AddIndex(
            model_name='recepta',
            index=models.Index(fields=['titol'], name='receptes_re_titol_24e00e_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['nom'], name='receptes_in_nom_c132c3_idx'),
        ),
    ]
