# Generated by Django 2.1.7 on 2019-03-14 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField()),
                ('data_creacio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_programat', models.DateTimeField(blank=True, null=True)),
                ('data_consumit', models.DateTimeField(blank=True, null=True)),
                ('actiu', models.BooleanField(default=True)),
            ],
        ),
    ]
