# Generated by Django 2.1.7 on 2019-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passa',
            name='descripcio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='recepta',
            name='foto',
            field=models.ImageField(default='/no-img.jpg', upload_to='fotos/'),
        ),
    ]
