# Generated by Django 2.1.7 on 2019-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0003_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
