# Generated by Django 2.1.7 on 2019-03-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0005_comentari_mesura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptaIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='mesura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='receptes.Mesura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptaingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptes', to='receptes.Ingredient'),
        ),
        migrations.AddField(
            model_name='receptaingredient',
            name='recepta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptes.Recepta'),
        ),
        migrations.AddField(
            model_name='recepta',
            name='ingredients',
            field=models.ManyToManyField(through='receptes.ReceptaIngredient', to='receptes.Ingredient'),
        ),
    ]
