# Generated by Django 2.1.7 on 2019-03-21 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0006_auto_20190320_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentari',
            old_name='autor',
            new_name='titol',
        ),
        migrations.AddField(
            model_name='recepta',
            name='dificultat',
            field=models.CharField(choices=[('F', 'Fàcil'), ('M', 'Mitjana'), ('D', 'Difícil')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='recepta',
            name='racions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='temps_preparacio',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='temps_total',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='recepta',
            name='thermomix',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mesura',
            name='nom',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='recepta',
            name='data_consumit',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='recepta',
            name='data_creacio',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='recepta',
            name='data_programat',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
