# Generated by Django 2.1.7 on 2019-03-25 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0007_auto_20190321_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='mesura',
            options={'ordering': ['nom']},
        ),
        migrations.RenameField(
            model_name='recepta',
            old_name='title',
            new_name='titol',
        ),
        migrations.AlterField(
            model_name='comentari',
            name='data_creacio',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['nom'], name='receptes_in_nom_c132c3_idx'),
        ),
        migrations.AddIndex(
            model_name='recepta',
            index=models.Index(fields=['titol'], name='receptes_re_titol_24e00e_idx'),
        ),
        migrations.AddIndex(
            model_name='recepta',
            index=models.Index(fields=['descripcio'], name='receptes_re_descrip_980e7b_idx'),
        ),
    ]
