# Generated by Django 2.1.7 on 2019-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0008_auto_20190325_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepta',
            name='foto',
            field=models.ImageField(default='media/fotos/no-img.jpg', upload_to='media/fotos/'),
        ),
    ]
