# Generated by Django 2.1.7 on 2019-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0009_recepta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepta',
            name='foto',
            field=models.ImageField(default='static/media/fotos/no-img.jpg', upload_to='static/media/fotos/'),
        ),
    ]
