# Generated by Django 2.1.7 on 2019-04-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0010_auto_20190325_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='mesura',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Mesures'},
        ),
        migrations.AlterModelOptions(
            name='recepta',
            options={'verbose_name_plural': 'Receptes'},
        ),
        migrations.RemoveIndex(
            model_name='recepta',
            name='receptes_re_descrip_980e7b_idx',
        ),
        migrations.AlterField(
            model_name='recepta',
            name='foto',
            field=models.ImageField(default='/fotos/no-img2.jpg', upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='recepta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receptes.Recepta'),
        ),
        migrations.AddField(
            model_name='recepta',
            name='categories',
            field=models.ManyToManyField(related_name='receptes', to='receptes.Categoria'),
        ),
    ]
