# Generated by Django 2.1.7 on 2019-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0011_auto_20190405_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='recepta',
        ),
        migrations.AlterField(
            model_name='recepta',
            name='categories',
            field=models.ManyToManyField(to='receptes.Categoria'),
        ),
    ]
