# Generated by Django 2.1.7 on 2019-04-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0012_auto_20190405_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('recepta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptes.Recepta')),
            ],
        ),
    ]
