# Generated by Django 2.1.7 on 2019-04-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0013_passes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passes',
            new_name='Passa',
        ),
        migrations.AlterModelOptions(
            name='passa',
            options={'verbose_name_plural': 'Passes'},
        ),
    ]
