# Generated by Django 2.1.7 on 2019-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0014_auto_20190405_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passa',
            options={'ordering': ['recepta__nom', 'ordre'], 'verbose_name_plural': 'Passes'},
        ),
        migrations.AddField(
            model_name='passa',
            name='descripcio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='passa',
            name='ordre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
