# Generated by Django 2.1.7 on 2019-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0015_auto_20190405_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passa',
            options={'ordering': ['recepta__titol', 'ordre'], 'verbose_name_plural': 'Passes'},
        ),
        migrations.AlterField(
            model_name='passa',
            name='descripcio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
