# Generated by Django 2.1.7 on 2019-04-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptes', '0016_auto_20190405_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passa',
            name='recepta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='receptes.Recepta'),
        ),
    ]
